"""empty message

Revision ID: af532dd33bdf
Revises: 
Create Date: 2017-08-17 15:11:16.800305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af532dd33bdf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('polls') as batch_op:
    	batch_op.drop_column('status')
    op.add_column('topics', sa.Column('status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topics', 'status')
    op.add_column('polls', sa.Column('status', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
